/**:
  ros__parameters:
    enable_sync: true
    enable_rgbd: true
    enable_gyro: false
    enable_accel: false
    enable_infra1: false
    enable_infra2: false
    pointcloud.enable: true
    align_depth.enable: true
    spatial_filter.enable: true
    temporal_filter.enable: true
